# Distance between two trajectories

In order to find the distance between two time series of data stored in matrices A and B, choose one as the reference trajectory, say A. Now we find the distance of B w.r.t A in the following manner: 
- Traverse through the points of B.
- For each point in B, find its distance from every point in A.
- Store the minimum of all these distances. So each point in B has a corresponding shortest distance in A
- Take the average of all the shortest distances.

In [1]:
import numpy as np
from numpy.linalg import norm

In [3]:
A = np.random.rand(3, 100)
B = np.random.rand(3, 10)

# Compute the distance from B to A
# The distance from B to A is the minimum of the distances from each point in A to B

dist = norm(A[:, :, None] - B[:, None, :], axis=0).min(axis=0)
print(dist)

[0.116692   0.16263667 0.13760027 0.1132868  0.19393398 0.21723697
 0.10089498 0.13180178 0.03957028 0.12215778]


In [5]:
A.shape

(3, 100)

In [6]:
B.shape

(3, 10)

In [7]:
A[:, :, None].shape

(3, 100, 1)

In [8]:
B[:, None, :].shape

(3, 1, 10)

In [10]:
(A[:, :, None] - B[:, None, :]).shape

(3, 100, 10)

In [32]:
# Array A of shape (3, 3)
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Array B of shape (3, 2)
B = np.array([[10],
              [20],
              [30]])

# Broadcasting B to shape (2, 3) and performing element-wise subtraction
result = A[:, :, None] - B[:, None, :]

print(result)

dist = norm(result, axis=0)
print(dist)

[[[ -9]
  [ -8]
  [ -7]]

 [[-16]
  [-15]
  [-14]]

 [[-23]
  [-22]
  [-21]]]
[[29.42787794]
 [27.80287755]
 [26.19160171]]


In [33]:
(8**2 + 15**2 + 22**2)**0.5

27.80287754891569

In [24]:
A[:, :, None].shape

(3, 3, 1)

In [25]:
B[:, None, :].shape

(3, 1, 2)